version: '3'

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile-test
    environment:
      - CI=true
      - REACT_APP_WEBSITE_URL=https://sanbase.stage.internal.santiment.net
    command: yarn test --ci
